### ISSUE TITLE
[ENHANCEMENT] Add installation instructions

### ISSUE THREAD

**Issue by mterczynski** [BenHerbst/idaesbasic#27]
**Describe the enhancment**
Add installation instructions

"(1) Downloaad and install the app for windows or linux." - I think this could be expanded a bit, it's not clear for me how I can achieve this step. Please keep in mind that I do not program in Java (although I have some knowledge on how to setup JDK & JRE, Maven)

**Comment by BenHerbst** [comment]
There is no need to setup jdk or jre as it is bundled with the .exe or .deb via jpackage. It is just an installer you can find at: https://github.com/BenHerbst/idaesbasic/releases/tag/0.9.1 if you use Windows. The newest version doesn't has a Linux version published yet as I am busy with other projects ( not here on Github ) but as I use Linux as my daily driver for some months now, I could create a .deb but it would only be for Debian. I don't know if you use Linux but then I would just download the .jar file and execute it with Java 17, the .jar should have everything you need. The source code is at https://github.com/BenHerbst/idaesbasic/tree/0.9.1 for the current release. You can also download the .exe at https://www.softpedia.com/get/Office-tools/Other-Office-Tools/Idaesbasic.shtml as someone published it there. I will take the time to update the readme, thank you for this enhancment :). I don't know how to publish java projects on Flathub ( A well known cross Linux app store, if anyone knows how to do that for java applications please post it here.

**Comment by BenHerbst** [comment]
https://github.com/BenHerbst/idaesbasic/commit/730f717bb1c2b31052877e0ec2fc213d05985c22

**Comment by mterczynski** [comment]
I didn't know the installer was available under releases and wasn't event aware there could be some downloadable files.
I'm a Windows user so you've fixed the issue for me.

Thanks for the readme improvements!
