### ISSUE TITLE
Possible enhancements

### ISSUE THREAD

**Issue by not-AMM** [BenHerbst/idaesbasic#5]
Hey!

- [x] I've been trying Idaes for a day and found some things that can be improved. The first one occurs when you hover your mouse in the sidebar and it highlights blank lines;~~

![imagen](https://user-images.githubusercontent.com/43765089/138770737-0d0b9e36-6a15-4822-9633-b13c377e68c4.png)

- [ ] #8

- [x] The sidebar should show the folder instead of the full path, because if you use any cloud solution, it shows a non-attractive visualization like: `C:\Users\%USER%\OneDrive\Documents\%FOLDER%\Idaes`

- [x] You could move the data shown in the bottom bar to the right, so it doesn't look too long and you can take a quicklook without too much characters. Also, I think there's a typo in the "Messanges" showed in the bottom bar

![imagen](https://user-images.githubusercontent.com/43765089/138771613-11815dab-482d-4096-ba4a-93a68af0497c.png)

**Comment by BenHerbst** [comment]
I will change everything you said after I finished the kanban and calendar view ( Calendar view is finished, kanban is in progress ), except the text flow thing, I would need to recreate everything from todolist and kanban view and its not easy to create. I will add that feature in 1.0.0 stable release.

**Comment by BenHerbst** [comment]
![Screenshot 2021-11-04 160430](https://user-images.githubusercontent.com/83538916/140341886-bcf5d35f-0534-45fe-9cae-63a2a349daea.png)

**Comment by BenHerbst** [comment]
![Screenshot 2021-11-06 034021](https://user-images.githubusercontent.com/83538916/140595208-71748db3-4274-4972-8249-8d23469bc363.png)

**Comment by BenHerbst** [comment]
I now added everything you said, except the todo workflow
